### ISSUE TITLE
[Feature] Possible API Endpoints

### ISSUE THREAD

**Issue by aadibajpai** [psincraian/pepy#118]
So that a user could programmatically fetch download counts and so on. 
Eg. `api.pepy.tech/project/<package_name>/total` could return the total download count and so.

Would be quite useful.

**Comment by psincraian** [comment]
I am planning to build the front using React and consume all the data though an api, so this feature will be implemented in the future :blush: 

Can I ask what you will do with the api?

**Comment by aadibajpai** [comment]
@psincraian I'd use it to directly get the download count of a package I made to dynamically format my resume with it. Right now I need to use bs4 to scrape the page. Basically this, https://github.com/aadibajpai/DynamicLaTeXResume

**Comment by astrom-tom** [comment]
I allowed my self to create a simple python program that scrap pepy.tech. It is called stpip and available in pip.

**Comment by psincraian** [comment]
Hi @aadibajpai and @astrom-tom,

I just added two api endpoints:
  - https://pepy.tech/api/projects returns the same list as in index
  - https://pepy.tech/api/projects/<project_id> returns the downloads of that project

Hope this can help you :blush:

**Comment by aadibajpai** [comment]
That's helpful, thanks!

**Comment by aadibajpai** [comment]
@psincraian is the API down? my applications started giving a 500 since no data is returned 😶

**Comment by astrom-tom** [comment]
@psincraian 
Yep there is a problem for me too with stpip. I can not scrap the webpage anymore (the numbers of download are not in the html page anymore...)

**Comment by psincraian** [comment]
@aadibajpai @astrom-tom sorry, the API url changed to https://api.pepy.tech/api/projects/requests

**Comment by aadibajpai** [comment]
> Hi @aadibajpai and @astrom-tom,
> 
> I just added two api endpoints:
> 
> * https://pepy.tech/api/projects returns the same list as in index
> * https://pepy.tech/api/projects/<project_id> returns the downloads of that project
> 
> Hope this can help you 😊

Is it possible to also have the monthly and daily count? That way a user could track growth rate etc.

**Comment by psincraian** [comment]
@aadibajpai currently no, but if you want you can add it, It should not be to difficult 😄

**Comment by aadibajpai** [comment]
> @aadibajpai currently no, but if you want you can add it, It should not be too difficult 😄
I wish I could do it myself but I'm not sure how 😶

**Comment by psincraian** [comment]
@aadibajpai if you wish I could guide and help you 😄 Maybe the first thing is to try to have the environment in local. Read the prerequisites and the start environment section: https://github.com/psincraian/pepy#prerequisites

If you have any doubt or issue contact me
