### ISSUE TITLE
[Feature] Allow passing arguments to `shields.io` badges

### ISSUE THREAD

**Issue by althonos** [psincraian/pepy#122]
Hi !

Since badges are generated using `shields.io` it would be great if users could also control the styling, possibly by passing the HTTP query arguments to `shields.io` directly. I'm an avid fan of the flat-square style, and would love to use it with badges from `pepy.tech` to display on my projects ! :wink:

**Comment by psincraian** [comment]
Hi @althonos,

My plan is to add some api endpoints and then you could use the shields.io endpoint feature:  https://shields.io/endpoint :smile:

**Comment by althonos** [comment]
Actually shields added download count badges for PyPI, and I didn't notice, so I'm using these. But I'm still redirecting to Pepy.tech :wink:

**Comment by MaxHalford** [comment]
Hey @psincraian, is this feature available now? Can we use [https://shields.io/endpoint](https://shields.io/endpoint)?

**Comment by althonos** [comment]
@MaxHalford : I'm using it currently for my project named `pronto`: `https://img.shields.io/badge/dynamic/json?style=flat-square&color=303f9f&maxAge=86400&label=downloads&query=%24.total_downloads&url=https%3A%2F%2Fapi.pepy.tech%2Fapi%2Fprojects%2Fpronto` 

and I get the following badge: [![Downloads](https://img.shields.io/badge/dynamic/json?style=flat-square&color=303f9f&maxAge=86400&label=downloads&query=%24.total_downloads&url=https%3A%2F%2Fapi.pepy.tech%2Fapi%2Fprojects%2Fpronto)](https://pepy.tech/project/pronto)

**Comment by MaxHalford** [comment]
Cheers @althonos!

**Comment by gnikit** [comment]
@althonos Do you know of a way to abbreviate the downloads e.g. from 494248 to 494k?

**Comment by althonos** [comment]
@gnikit : Unfortunately not, there is no abbreviated count in the JSON response from the PePy API, and shields.io doesn't have a way to do that either.
