### ISSUE TITLE
Continous loading indicator while searching with newly added project

### ISSUE THREAD

**Issue by adiralashiva8** [psincraian/pepy#157]
I have recenlty hosted my project in PYPI and when i'm trying to search project in [Pepy Tech](https://pepy.tech) continous loading indicator is displaying

![Loading](https://user-images.githubusercontent.com/12430515/64966175-f147a880-d8bb-11e9-8e19-28dcfc4e0f46.JPG)

My Project: pytest-metrics

URL - [https://pepy.tech/project/pytest-metrics](https://pepy.tech/project/pytest-metrics)

If we could show some no data availlable or some message that could be good for user

**Comment by psincraian** [comment]
Good catch, I will fix it :+1:

**Comment by psincraian** [comment]
Fixed, now we show a 404 page :-)
