### ISSUE TITLE
Existing project return 404

### ISSUE THREAD

**Issue by fabiocaccamo** [psincraian/pepy#191]
Hi, 
as you can see the badge for this project (recently added) doesn't work:
https://github.com/fabiocaccamo/django-extra-settings

Searching for the project on the `PePy` website return a 404:
https://pepy.tech/project/django-extra-settings

**Comment by psincraian** [comment]
Hi @fabiocaccamo, the website only updates once a day, and I think the project was published on the same day so pepy.tech has no data.

Now you can see the data on the website :-)
