### ISSUE TITLE
Wrong units for badges

### ISSUE THREAD

**Issue by jacobtomlinson** [psincraian/pepy#192]
It looks like requests has been downloaded `1G` times! One gazillion times! That's huge! 😁

I think the units are set to bytes, which means requests is showing as being downloaded `1 Giga` times. As the shorthand for millions and Mega is both `M` and they are both at the factor of `1e6` this has not been noticed. But when a number moves into the `1e9` range things are broken.

![image](https://user-images.githubusercontent.com/1610850/74730630-6722b800-523e-11ea-9d1e-ff879fa07bca.png)

**Comment by jacobtomlinson** [comment]
Just spotted #180 which attempted to resolve this.

**Comment by psincraian** [comment]
Hi, as there is a demand for it, I will work on an option to personalize the badge :-)

**Comment by psincraian** [comment]
Now you can personalize the badge on pepy.tech: https://pepy.tech/project/requests/personalized-badge

This will solve the issue 😊 Any feedback is more than welcome
