### ISSUE TITLE
Way to add "All" to the versions graph

### ISSUE THREAD

**Issue by sethmlarson** [psincraian/pepy#205]
Would be nice to visualize how the total downloads changes per day.

**Comment by psincraian** [comment]
Spoiler: it will be available in the next feature with the glob search :blush:

**Comment by psincraian** [comment]
Now the feature is on production. For anyone interested, you can use the glob pattern in the versions search box so that you can search for: `2.*` or `3.*`.

To view the total number of downloads, you can use `*`.
