### ISSUE TITLE
Change color of the badge

### ISSUE THREAD

**Issue by Zethson** [psincraian/pepy#211]
Hi,

I would like to change the color of my badge. Any way I can do that?

**Comment by psincraian** [comment]
Hi, official is not supported currently but I plan to improve the badge generation in the near future.

Meanwhile you can use the shields : https://img.shields.io/badge/dynamic/json?style=flat-square&color=303f9f&maxAge=86400&label=downloads&query=%24.total_downloads&url=https%3A%2F%2Fapi.pepy.tech%2Fapi%2Fprojects%2Frequests

![shields example](https://img.shields.io/badge/dynamic/json?style=flat-square&color=303f9f&maxAge=86400&label=downloads&query=%24.total_downloads&url=https%3A%2F%2Fapi.pepy.tech%2Fapi%2Fprojects%2Frequests)

**Comment by Zethson** [comment]
Thanks, that works.

**Comment by psincraian** [comment]
Now you can personalize the badges on pepy.tech: https://pepy.tech/project/requests/personalized-badge

This feature fixes your problem 😊 Any feedback is more than welcome
