### ISSUE TITLE
My package is not showing.

### ISSUE THREAD

**Issue by Soheab** [psincraian/pepy#217]
On PYPI: https://pypi.org/project/alexflipnote.py/

Meanwhile pepy: https://pepy.tech/project/alexflipnote.py

**Comment by hugovk** [comment]
Check the normalised name:

https://pepy.tech/project/alexflipnote-py

https://pypi.org/project/alexflipnote-py/

How it works:

https://www.python.org/dev/peps/pep-0503/#normalized-names

Perhaps pepy.tech could normalise too?

**Comment by Soheab** [comment]
> Check the normalised name:
> 
> https://pepy.tech/project/alexflipnote-py
> 
> https://pypi.org/project/alexflipnote-py/
> 
> How it works:
> 
> https://www.python.org/dev/peps/pep-0503/#normalized-names
> 
> Perhaps pepy.tech could normalise too?

ohh thanks! i didn't think of that

**Comment by psincraian** [comment]
Fixed, now it should work 😄
