### ISSUE TITLE
sum vs total?

### ISSUE THREAD

**Issue by nschloe** [psincraian/pepy#223]
I've looked at pepy.tech for the first time, and the numbers appeared too high to me. In the statistics, I see the two numbers `sum` and `total`

![screenshot](https://user-images.githubusercontent.com/181628/88531250-d4fbb880-d002-11ea-9f43-002d9e667049.png)

and it's unclear to me what `total` is.

**Comment by hugovk** [comment]
At a guess:

* Sum is the number of downloads for the **selected** versions shown
* Total is the number of downloads for **all** versions

**Comment by psincraian** [comment]
Yes, @hugovk is right :-)

**Comment by nschloe** [comment]
The wording here can certainly be improved.
