### ISSUE TITLE
large discrepancies comparing with pypistats

### ISSUE THREAD

**Issue by nschloe** [psincraian/pepy#224]
I'm sure you're aware that https://pypistats.org/ offers similar statistics as pepy.tech. There is however a large discrepancy between the data. For one project of mine it's 1k vs 3.9k downloads a month (see below). Any idea what may be causing this? Got to say I distrust the 3.9k (which is an average of 130 per day) looking at pepy's own graph below.

---

https://pypistats.org/packages/quadpy

![screenshot](https://user-images.githubusercontent.com/181628/88685524-4f593500-d0f6-11ea-8bf5-a262247645e5.png)

---

https://pepy.tech/project/quadpy

![screenshot](https://user-images.githubusercontent.com/181628/88685630-6dbf3080-d0f6-11ea-92e5-0bb66e1a7f68.png)

---

![screenshot](https://user-images.githubusercontent.com/181628/88685878-bd9df780-d0f6-11ea-921e-e2fd3fd127a0.png)

**Comment by hugovk** [comment]
pypistats excludes downloads from mirrors:

* https://pypistats.org/faqs#why-are-the-cumulative-download-counts-different-from-the-sum-of

Also, there's currently data missing from July 19 onwards at pypystats:

* https://github.com/crflynn/pypistats.org/issues/29

**Comment by nschloe** [comment]
> Also, there's currently data missing from July 19 onwards at pypystats:

The count didn't get updated either, so this doesn't influence the total number from pypistats.org. 

> pypistats excludes downloads from mirrors:

I don't think this is the reason. Just look at pepy's own graphs and the "total" numbers. The "total" count suggests and average of 130 downloads a day. In the graphs, this number is only ever reached on two days, and is otherwise _far_ below it.

**Comment by hugovk** [comment]
# pepy

Let's use `*` on pepy to show all versions, not just the most recent three:

[https://pepy.tech/project/quadpy?versions=*](https://pepy.tech/project/quadpy?versions=*)

![image](https://user-images.githubusercontent.com/1324225/88797537-25624a00-d1ac-11ea-9be2-b0561fff1ce6.png)


The peak on 2020-07-11 has 408 downloads.

# pypistats

Let's zoom in a bit and check the same day:

![image](https://user-images.githubusercontent.com/1324225/88797417-fb108c80-d1ab-11ea-9d8a-ad7025f26563.png)

408 with mirrors, and 264 without.

A quick check and the previous day and next day also match (with mirrors).

**Comment by psincraian** [comment]
Thanks for the analysis @hugovk  👏👏👏 

pepy.tech gets the data from the official repository (same as pypistats I think). So the numbers should be the same :-)

**Comment by hugovk** [comment]
Perhaps pepy.tech should also exclude mirrors? 

See the linked FAQ above, and:

> Downloads by mirrors are intentionally excluded from download breakdowns because they do not represent end-users of the software.

**Comment by nschloe** [comment]
> Perhaps pepy.tech should also exclude mirrors?

I'd find that a good idea. For every version of my packages, no matter how old and outdated, I see a solid ~25 downloads a month. Those _must_ be from mirrors. Those downloads account for about +50% of the "actual" downloads, sometimes more.

**Comment by psincraian** [comment]
Then this is more related to that: https://github.com/psincraian/pepy/issues/164 I will try to prioritize this :-) By the end of the month I will run a pool to choose on what to focus next 😊 

@nschloe can I close this issue as it's more related with the other one?

**Comment by nschloe** [comment]
Closing in favor of #164.

**Comment by hugovk** [comment]
Sounds good!

Should there be another issue to show charts without mirrors too, or be part of #164?

**Comment by psincraian** [comment]
@hugovk when we implement #164 adding it to the charts it should be straightforward.
