### ISSUE TITLE
show [*] (all versions) by default

### ISSUE THREAD

**Issue by nschloe** [psincraian/pepy#229]
The pepy badge shows the count for all (`*`) versions, but this value is not included by default in the graphs. It is not clear that `*` is a valid filter at all, either. It'd make things clearer if `*` was included in the graphs by default.

**Comment by psincraian** [comment]
Good suggestion! 😊 I agree that it's not easy to find it.

**Comment by psincraian** [comment]
Now I show an example of the `*` operator
