### ISSUE TITLE
Need label parameter

### ISSUE THREAD

**Issue by pbelskiy** [psincraian/pepy#230]
Hello, thanks for your project, recently I've changed my PyPI downloads badge from shields.io to your one, so could I change
`downloads` to `Downloads`?

It's looks not so cute when one of inline bars isn't capitalised : https://github.com/pbelskiy/aiojenkins

**Comment by psincraian** [comment]
Now you can personalize the badge https://pepy.tech/project/requests/personalized-badge

This fixes your issue 😊 Any feedback is more than welcome
