### ISSUE TITLE
Total Downloads Decreasing

### ISSUE THREAD

**Issue by seanlaw** [psincraian/pepy#239]
Thank you for this package! I manage the `stumpy` Python package and I query daily downloads via:

```
https://api.pepy.tech/api/projects/stumpy
```

Today (September 19, 2020), I noticed that the total downloads count actually went down compared to yesterday:

```

{"id": "stumpy", "total_downloads": 36691, "downloads": {"2020-09-16": 158, "2020-09-15": 176, "2020-09-14": 90, "2020-09-13": 110, "2020-09-12": 117, "2020-09-11": 78, "2020-09-10": 79, "2020-09-09": 80, "2020-09-08": 120, "2020-09-07": 113, "2020-09-06": 113, "2020-09-05": 60, "2020-09-04": 115, "2020-09-03": 151, "2020-09-02": 235, "2020-09-01": 311, "2020-08-31": 124, "2020-08-30": 240, "2020-08-29": 92, "2020-08-28": 117, "2020-08-27": 109, "2020-08-26": 118, "2020-08-25": 206, "2020-08-24": 241, "2020-08-23": 113, "2020-08-22": 55, "2020-08-21": 86, "2020-08-20": 189}}
```

Yesterday (September 18, 2020), had a total download of "36801". In fact today's total download number seems to be the same as September 17 (two days ago).

**Comment by psincraian** [comment]
Hi @seanlaw! Yes, sorry. I had a problem with the server, and I needed to restore a backup from 2 days ago. Now I'm importing the downloads from the last two days and it should be the same in a couple of hours 😊

**Comment by seanlaw** [comment]
Thank you!

**Comment by seanlaw** [comment]
@psincraian Sorry to bother you again and you may already be aware of this but It looks like the downloads are "off" again. It looks like the numbers from the last two days aren't updating correctly.

**Comment by psincraian** [comment]
Hi @seanlaw, yes. I'm taking a look, seems I need to buy a bigger server 👀

**Comment by seanlaw** [comment]
Sincerely, I'm sure that you are on top of these things and your time is very valuable so please do not hesitate to let me know if my notifications/comments are not actually helpful. Again, I understand that this is free service and very much appreciate your attention to this!

**Comment by psincraian** [comment]
hi @seanlaw, sorry if it sounded rude; it was not my intention. I find your comments helpful, I have alerts, but they may fail also. So every comment here I found it useful 😊 

I try to do my best to keep the service up. Usually, all of these things are quite fast to fix. If everything goes fine in a couple of hours, all the downloads from yesterday should be there.

**Comment by seanlaw** [comment]
Oh, no! You were not rude at all. I was my concerned that my brevity and directness may come across as sounding entitled or demanding. Glad to see that we are on the same page do thank you! 🙏

**Comment by seanlaw** [comment]
@psincraian It looks like the download counts failed to update today. 😅

**Comment by psincraian** [comment]
yep 🤦 I need to invest some time in reducing the RAM consumed when updating downloads...


Thanks for the notice @seanlaw

**Comment by seanlaw** [comment]
Good morning (and happy new year), @psincraian! You probably saw this already but it looks like yesterday's (January 24, 2021) downloads did not update successfully. 🙏

**Comment by psincraian** [comment]
Hey @seanlaw 

Yes, I'm aware. Here I have contacted PyPI maintainer because the data is not there https://twitter.com/psincraian/status/1353603984624394245?s=21

**Comment by seanlaw** [comment]
Awesome! Now, I can follow you on Twitter 😄
