### ISSUE TITLE
Badge with week in url path not working

### ISSUE THREAD

**Issue by R1j1t** [psincraian/pepy#252]
Firstly, let me just say how amazing the this project is. The is minimalistic and has all the necessary features for me! But recently I realized that the url in my downloads badge is not working. 

Below is the URL:
https://pepy.tech/project/contextualspellcheck/week

Current Behavior:
404 error

Expected Behavior:
Page should load with the information. Like it used to open earlier.

Another reason for opening this bug is in my [project page](https://pepy.tech/project/contextualspellcheck) the `/week` download still shows the same URL.

**Comment by psincraian** [comment]
Hi @R1j1t the correct badge image url is the following

https://pepy.tech/**badge**/contextualspellcheck/week 

Or you can also use the new version which has one less redirect https://static.pepy.tech/badge/contextualspellcheck/week

Hope this helps 😊

**Comment by psincraian** [comment]
@R1j1t does this fixes your issue?

**Comment by R1j1t** [comment]
@psincraian what I meant is if i copy the Badge markdown from the project page, it looks something like below:

`[![Downloads](https://pepy.tech/badge/contextualspellcheck/week)](https://pepy.tech/project/contextualspellcheck/week)`

The badge image url i.e. `https://pepy.tech/badge/contextualspellcheck/week` I dont have an issue with. But, the hyperlink on the badge i.e. `https://pepy.tech/project/contextualspellcheck/week` when opened in a browser gives 404 error.

Above one is the default badge markdown which gets copied to clipboard and hence I think some else using the week or month badge, the hyperlink wold give 404. Please let me know if you need more information. I will attach some screenshots.

**Comment by R1j1t** [comment]
Great, happy to be of help!

**Comment by psincraian** [comment]
Fixed, now it should work 😄 

Thanks for the report! 🙇
