### ISSUE TITLE
'Buy me a coffee' - badge bug

### ISSUE THREAD

**Issue by finnmglas** [psincraian/pepy#267]
Hey Petru, I just found this bug: 

[![image](https://user-images.githubusercontent.com/40366035/101278998-6522e900-37bf-11eb-809b-2908b0eba6c7.png)](https://pepy.tech/project/gitpm)

I made a snapshot of the current state using the [wayback machine](https://web.archive.org/web/20201206113616/https://pepy.tech/project/gitpm).

I love using pepy, keep up the great work!

**Comment by finnmglas** [comment]
This issue should likely be migrated to [pepy-front](https://github.com/psincraian/pepy-front).

**Comment by psincraian** [comment]
Hey @finnmglas, I will fix it. Thanks 😊

**Comment by psincraian** [comment]
fixed :-)
