### ISSUE TITLE
Badge Not Updating Daily

### ISSUE THREAD

**Issue by boba-and-beer** [psincraian/pepy#277]
Hi, 

I am trying to use pepy.tech badges on my repository - but they don't seem to be properly updating until I repaste the link into the Markdown and change the color. Is there any fix for this? (See https://github.com/vector-ai/vectorhub for an example).
The badge numbers seem to be stuck on 5.9k but upon clicking and visiting the link, they are actually 6.5K (as well as checked on the stats).

Also let me know if this is not the right place to be asking this question as I cannot seem to find a better forum so placing my question here for now.

P.S. Thanks for open-sourcing this and making adding badges to repositories easily!

**Comment by boba-and-beer** [comment]
Resolved. To do with GitHub caching system as opposed to pepy tech badges.

**Comment by hetpandya** [comment]
Hi @boba-and-beer, how did you solve this? I am having the same issue

**Comment by psincraian** [comment]
Hey @hetpandya it's explained here: https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/about-anonymized-urls#removing-an-image-from-camos-cache

**Comment by hetpandya** [comment]
Hi @psincraian, thanks for the reference. I went through it. However I'm not sure if I could understand it. Could you guide me as what changes do I need to make in my repo?
For e.g. I've put the download count [here in my repo](https://github.com/hetpandya/youtube_tts_data_generator).
Thanks!

**Comment by boba-and-beer** [comment]
@hetpandya my solution was to write a github action that re-downloaded the badges daily and pushed to the github repository - thus updating itself automatically daily

**Comment by hetpandya** [comment]
Thanks @boba-and-beer! I shall give that a try with my repository too
