### ISSUE TITLE
Vectorized or greater quality Pepy logo

### ISSUE THREAD

**Issue by mondeja** [psincraian/pepy#283]
Hello. First of all, thank you for your work with Pepy, it looks great!

I'm a maintainer of [simple-icons](https://github.com/simple-icons/simple-icons) project, which is the main provider for https://shields.io badge icons. The Alexa ranking indicator for Pepy ([~600K](https://www.alexa.com/siteinfo/pepy.tech)) is approaching the minimum position that a brand requires to be included in simple-icons (500K or 5K Github stars). When included, we could generate an included logo badge of downloads showing the Pepy logo using https://shields.io.

But for this, we need an available image of the Pepy logo in vector format (SVG, EPS ...) or a raster image (like the [current logo](https://github.com/psincraian/pepy/blob/5566d06fe48e0f296fb1d2f91fa585393d5c251a/docs/logo.png)) but of higher quality. Could you provide it?

**Comment by psincraian** [comment]
Hey @mondeja,

Wow, good news 😊🚀 Thanks for the explanation, I didn't know about you. Here you can find the logo in SVG format: https://github.com/psincraian/pepy-front/blob/master/public/logo.svg

**Comment by mondeja** [comment]
Thank you @psincraian :pray:
