### ISSUE TITLE
Caching of Personalized Badges

### ISSUE THREAD

**Issue by MiWeiss** [psincraian/pepy#293]
I'm using a personalized badge in a github readme ([here](https://github.com/HunterMcGushion/docstr_coverage)) and noticed that the badge does not update over multiple days (i.e., since it was added to the readme): At the moment, the badge shows 94k downloads, where the reported number on pepy.tech has been higher than 95k for a couple of days.

Upon closer inspection, I noticed that the caching headers for personalized badges are different from the caching headers for 'regular badges. Amongst other things, it appears the `cache-control:max-age`  is not set for personalized badges (set to 1 day for regular badges).

**Comment by samzhangjy** [comment]
Any updates on this issue? I'm having the same problem here.

**Comment by psincraian** [comment]
Fixed by @MiWeiss, many thanks for your contribution 😊
