### ISSUE TITLE
Add badge with last month downloads

### ISSUE THREAD

**Issue by amirouche** [psincraian/pepy#30]
I think 'last month downloads' is more relevant that overall download.

Let me know if you agree with this I will work on a patch then.

Tx again for this awesome project.

**Comment by psincraian** [comment]
Hi @amirouche! 

Many thanks for posting this issue. I think that it's a very interesting feature so if you want to implement it you are free to do it :rocket:  

I will post some suggestions of how I would like the code to be implemented but you are free to implement as you wish:
* I thought the endpoint to be something like `https://pepy.tech/badge/requests/monthly`
* I would like the monthly downloads to be in the `Project` model. Currently this data is not projected in the database, so take into account if you need to project it or you can compute it on demand.
* I know that not all the code is tested, but I expect that all new code will be tested

If you have some doubts don't hesitate to ask me :blush:

**Comment by psincraian** [comment]
Done [![Downloads](https://pepy.tech/badge/requests/month)](https://pepy.tech/project/requests) 😊
