### ISSUE TITLE
pepy.tech project endpoint not responding

### ISSUE THREAD

**Issue by fcakyon** [psincraian/pepy#302]
I have tried with many vpns. Cannot get any package result from pepy.tech/project/ endpoint.

**Comment by samuelcolvin** [comment]
I'm getting  the same thing, first saw this last night.

I just see the loading animation indefinitely.

**Comment by zoj613** [comment]
Same with pystats.org. Download stats have been frozen since the 22nd of March.

**Comment by lunAr-creator** [comment]
I have the same issue. Going to pepy and trying to look at a package just yields a indefinete loading loop. Not sure what has happened.

**Comment by cmdvmd** [comment]
I have the same problem, and the pepy badges I included in my README(s) are not working either
<img width="79" alt="badge" src="https://user-images.githubusercontent.com/55916643/112725863-b7178800-8ef0-11eb-9878-c10790b5fd33.PNG">

**Comment by lewiuberg** [comment]
Same here. And the shield is not working either ![image](https://user-images.githubusercontent.com/43423020/112730025-72f7a800-8f2f-11eb-9028-11af0a388ca8.png)![image](https://user-images.githubusercontent.com/43423020/112730030-78ed8900-8f2f-11eb-9df1-ac13f48deca9.png)

**Comment by fcakyon** [comment]
it seems to be fixed now.

**Comment by psincraian** [comment]
Sorry, the mongodb was down. I will backfill missing data

**Comment by lewiuberg** [comment]
The issue seems to be back

**Comment by lunAr-creator** [comment]
unfortunately the issue is back. maybe it is the same issue again with the mongodb as @psincraian said?

**Comment by cmdvmd** [comment]
The website is not working, but this time the badge is working

**Comment by psincraian** [comment]
It's back again, we had a problem with the server for two hours

**Comment by addypy** [comment]
It seems to be down again since the last few hours. @psincraian
