### ISSUE TITLE
Downloads Badge Cached | Not refreshing

### ISSUE THREAD

**Issue by rafiqhasan** [psincraian/pepy#341]
Hi Team

The downloads badge seems to be cached on github repo and is not refreshing even though the stats have change. Can you make sure you have set the cache-expiration correctly in the badges so that Github server doesn't cache the images.

Please check : https://github.com/github/markup/issues/224 and fix as per guidelines

Please change this line in https://github.com/psincraian/pepy/blob/master/pepy/infrastructure/web/__init__.py#L49 

    return Response(badge.image, mimetype="image/svg+xml", headers={"Cache-Control": "max-age=86400"})

to

    return Response(badge.image, mimetype="image/svg+xml", headers={"Cache-Control": "no-cache"})

**Comment by psincraian** [comment]
Hey, it's only me maintaining the project.

Currently pepy.tech runs on a quite small machine (4 GB of RAM and 2 CPUs) serving more than 8 million requests per month globally!

We have one contributor that pays for the server. If you want to contribute check our [Patreon](https://www.patreon.com/pepy) 

If we remove the cache we will get a lot more requests that would put the server down.
