### ISSUE TITLE
What is downloads=1G ?

### ISSUE THREAD

**Issue by rafiqhasan** [psincraian/pepy#346]
While checking the statistics for https://pepy.tech/project/numpy the download count should show 1B, but it shows 1G

```
PyPI link
https://pypi.org/project/numpy
Total downloads: 1,402,942,658
Total downloads - 30 days: 78,825,979
Total downloads - 7 days: 17,972,008
```

![image](https://user-images.githubusercontent.com/21009819/126354761-54f192be-720c-4641-90be-f59e8751905b.png)

**Comment by hugovk** [comment]
G = giga

https://github.com/psincraian/pepy/blob/9c8f574b807e62d1028620045444afcc7ba78dda/pepy/application/badge_service.py#L23

**Comment by rafiqhasan** [comment]
It should be B = Billion, this is a standard metric for counts. 

M, B, Q, T

**Comment by johann-petrak** [comment]
> It should be B = Billion, this is a standard metric for counts. We are not measuring bytes here :)
> 
> M, B, Q, T

I strongly disagree. B is not just not a standard "metric" it is also, unlike ISO metric prefixes, specific to the English languaga, e.g. "Billion" in German is DIFFERENT from "billion" in English (German: Million = 10E6, Milliarde = 10E9, Billion=10E12, Billiarde=10E15, English: Million=10E6, Billion=10E9 etc). 

Definitely lets stick with ISO here.

**Comment by rafiqhasan** [comment]
Better solution, give an option to the end user to choose ISO metrics or not. Not the whole world uses ISO everywhere and clearly there's a very big chunk of population which prefers NOT ISO.

**Comment by johann-petrak** [comment]
> Better solution, give an option to the end user to choose ISO metrics or not. Not the whole world uses ISO everywhere and clearly there's a very big chunk of population which prefers NOT ISO.

Most of the whole world uses ISO, except mainly the US where ISO is used in parallel with some medieval crazy other units. 
Since github and github stats are used globally, ISO is the common language that is understood by everyone.

**Comment by rafiqhasan** [comment]
Ok so let me assume its not possible to add a parameter because clearly there's a lot of resistance 🙂

**Comment by psincraian** [comment]
Hey @rafiqhasan you can personalize your badge here: https://pepy.tech/project/requests/personalized-badge
