### ISSUE TITLE
Total downloads rounded in badge ?

### ISSUE THREAD

**Issue by rafiqhasan** [psincraian/pepy#349]
Hi Team,

I can see for my library that the total downloads are 1.3K but the badge shows 1K isn't it quite misleading because for the visitors, the numbers have not moved at all in the last 3 days.

Shouldn't there be atleast one decimal of precision ?

[![Downloads](https://pepy.tech/badge/auto-tensorflow)](https://pepy.tech/project/auto-tensorflow)

**Comment by psincraian** [comment]
It depends on the scale, if you have 1M total downloads but only 1k downloads per day it will take some days to see the decimal increased.

I recommend you using the monthly or weekly badge because it will give you more dynamic content.
