### ISSUE TITLE
Unable to Load Stats

### ISSUE THREAD

**Issue by seanlaw** [psincraian/pepy#350]
Good morning! I noticed that `https://pepy.tech/project/Stumpy` and several other pages like `https://pepy.tech/project/Numpy` were unable to load this morning. However, the main page `https://pepy.tech/` loads fine but no searches could be performed. I wanted to report this in case it may be important.

**Comment by schosterbarak** [comment]
same here

**Comment by 2bndy5** [comment]
same. I'll check it again tomorrow

**Comment by dermasmid** [comment]
same here

**Comment by deepjyoti30** [comment]
+1

Just noticed the API is not able to load stats for any package. Even tried the official page, the request to the API just keeps on pending.

**Comment by 2bndy5** [comment]
Seems to be back up now

**Comment by seanlaw** [comment]
Yes! It is back up and running now. Thank you1
