### ISSUE TITLE
504 Gateway Timeout Trying to Access API

### ISSUE THREAD

**Issue by seanlaw** [psincraian/pepy#386]
I am trying to hit `https://api.pepy.tech/api/projects/stumpy` but have been seeing a 504 Gateway Timeout for about the past 3 hours. I hope this report is helpful

**Comment by seanlaw** [comment]
This appears to be resolved now. As always, thank you for your diligence! I really appreciate it

**Comment by psincraian** [comment]
Heye @seanlaw, yes! Sorry for the inconvenience
