### ISSUE TITLE
Pepy down

### ISSUE THREAD

**Issue by Spratiher9** [psincraian/pepy#387]
All my projects stats are down not able to get the download stats since the past 18 hours.

**Comment by schosterbarak** [comment]
@psincraian same here

**Comment by seanlaw** [comment]
@Spratiher9 @schosterbarak It appears to be resolved now (see https://github.com/psincraian/pepy/issues/386). Can you please confirm and close if true?

**Comment by Spratiher9** [comment]
Yep everything's working fine now.. Thanks @seanlaw

**Comment by psincraian** [comment]
hey, yep sorry. The server was down. The new data will be there in a few hours
