### ISSUE TITLE
Pepy stopped showing stats

### ISSUE THREAD

**Issue by Quantum-Codes** [psincraian/pepy#398]
Links: 
https://pepy.tech/project/Scraget
https://pypi.org/project/Scraget

**Problem:**
I used to number all my versions continuously(0.0.1 then 0.0.2 and so on).
Once I mistakenly left v0.1.5 and skipped from 0.1.4 to 0.1.6.
Since then pepy has stopped showing statistics of later versions.
I went back and created v0.1.5 but still it doesn't show stats of package beyond v0.1.4.

Here you can see I created v0.1.5 after few days https://pypi.org/project/ScraGet/0.2.0/#history

**Comment by boisgera** [comment]
Are you sure that it's not simply related to #391 ?

**Comment by Quantum-Codes** [comment]
Oops, I'm sorry.. this was maybe a coincidence that I made a mistake and stats aren't updated... https://github.com/psincraian/pepy/issues/391 I just saw it
