### ISSUE TITLE
Shorten badge version

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [psincraian/pepy#4]
I discovered your project today, very nice one.

I am able to obtain the following badge: [![Downloads](http://pepy.tech/badge/tensorlayer)](http://pepy.tech/project/tensorlayer)

However, I would like to be able to shorten it to 73k and not 73.44 thousands which takes a lot of place.
Is there any way to do this ?

**Comment by psincraian** [comment]
Done! 😊 Now the default badge versuon

**Comment by psincraian** [comment]
Done, many thanks for your suggestion 😊 now the default badge version is shorter.  You are not the first person asking this so I made the default badge shorter 👌 

In the future I will add an option to personalize the badge 😉
