### ISSUE TITLE
Update statistics more than once per day?

### ISSUE THREAD

**Issue by TylerYep** [psincraian/pepy#401]
Wondering if it is possible to update the statistics more than once per day (every 6 hours maybe?), or if it is a limitation of the dataset. Seeing downloads update more frequently is a big plus. 

Btw, thank you for the great website!

**Comment by psincraian** [comment]
Technically it's possible to do that, even faster than 6 hours. The only problem is money, every query on BigQuery costs money...

If you want to support us we have many platforms:
* [Github Sponsors](https://github.com/sponsors/psincraian)
* [Patreon](http://patreon.com/pepy)
* [Buymeacoffee](http://buymeacoffee.com/pepy)

**Comment by TylerYep** [comment]
Makes sense, thanks! I wasn't familiar with the dataset size, so I didn't realize the website was already exceeding the free tier.
