### ISSUE TITLE
service crashed

### ISSUE THREAD

**Issue by CNFeffery** [psincraian/pepy#415]
It just keep loading
![image](https://user-images.githubusercontent.com/49147660/154874243-9b94c014-c2e8-46c9-8991-6edd955f91e5.png)

**Comment by HanzCEO** [comment]
Happens to me too, badges also stop working
cc owner @psincraian

**Comment by schouxy53** [comment]
Happens to me too, can no longer see badges.

**Comment by DefTruth** [comment]
me too

**Comment by psincraian** [comment]
Fixed :-)
