### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by Carlover101** [psincraian/pepy#422]
I tried to log onto the website today on multiple devices, and it says that the site doesn't exist. Did the domain expire?

**Comment by Pactortester** [comment]
+1 Inaccessible

https://pepy.tech/

**Comment by oliver-zehentleitner** [comment]
Whats going on?

**Comment by johnbumgarner** [comment]
Some type of change happened yesterday. 

WHOIS shows this:

Created on 2018-03-10
Expires on 2022-03-10
Updated on 2022-03-15

**Comment by oliver-zehentleitner** [comment]
The domain pepy.tech is still unregistered :/

**Comment by hugovk** [comment]
The domain expired on 2022-03-10:

https://domains.google.com/registrar/search/whois/pepy.tech?hl=en&searchTerm=pepy.tech

There should still be a grace period of 30-60 days when it can be renewed.

I've emailed @psincraian in case he's not logged in here for a while.

**Comment by hotlittlewhitedog** [comment]
This project should be supported by The Python Foundation and hosted on their servers.

**Comment by psincraian** [comment]
Hey, sorry I was on holidays and missed the email of renewal 😢 Also, I needed to pay 66 euros to recover it and 38 to renew it! 👎 👎  Hopefully the DNS will propagate soon and you will be able to access it again

It's not a nice start of the 4th anniversary of pepy.tech 🎂

**Comment by psincraian** [comment]
Seems that the site is up again (at least for me). 

If anyone finds the website useful and want to contribute paying the bills here I post some links 🙏🏻:

- [PayPal](https://www.paypal.com/paypalme/psincraian)
- [BuyMeACoffe](https://www.buymeacoffee.com/pepy)
- [Patreon](https://www.patreon.com/pepy)

**Comment by oliver-zehentleitner** [comment]
I would like donate a few bugs via github sponsoring, would that be possible?

**Comment by psincraian** [comment]
hey @oliver-zehentleitner, I also have a Github Sponsors: https://github.com/sponsors/psincraian :-)

Thanks to all the people than donated, it really means a lot! :bowing_man:

**Comment by oliver-zehentleitner** [comment]
Thanks! Add this to your [FUNDING](https://github.com/psincraian/pepy/blob/master/.github/FUNDING.yml) file!
