### ISSUE TITLE
the statistics about different pip source base

### ISSUE THREAD

**Issue by dongrixinyu** [psincraian/pepy#437]
My pypi package `jionlp` is mainly been downloaded in China and often installed through different pip source base like below:
```
$ pip install jionlp -i https://mirrors.tuna.tsinghua.edu.cn
```
Im curious that if pepy could include different pip source base when doing statistics?
Thank you!

**Comment by psincraian** [comment]
Hey @dongrixinyu,

Sorry but mirrors usually don't expose data publicly. Always take the data from pepy.tech as a trend, as the number of downloads packages may be different: https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/
