### ISSUE TITLE
default versions displayed on package selection

### ISSUE THREAD

**Issue by gabis-precog** [psincraian/pepy#442]
As far as I can tell, on selecting a package, the statistics for the last 3 versions are shown.

The sort order of the versions may not be correct.

In my example:

https://pepy.tech/project/rsocket

shows the statistics for the last 3 dev versions, (0.3dev1, 0.3dev2, 0.3dev3) and not the release version (0.3)

**Comment by psincraian** [comment]
Now it should be fixed :-)
