### ISSUE TITLE
Combine all versions in display

### ISSUE THREAD

**Issue by cthoyt** [psincraian/pepy#473]
My project, `bioregistry` (https://pepy.tech/project/bioregistry), releases nightly, and therefore has a lot of releases. It doesn't seem to be possible to combine all versions, even though this is a pretty atypical scenario. Might be nice.

Note, from below, the following [link](https://pepy.tech/project/bioregistry?versions=*) only works if inside some markdown or HTML since the trailing asterick gets omitted (v important!)

**Comment by hugovk** [comment]
Use an asterisk:

https://pepy.tech/project/bioregistry?versions=*

**Comment by cthoyt** [comment]
That's great, thanks! then my suggestion would be to add a small element on the page that describes how to do this :)

**Comment by psincraian** [comment]
Thanks @hugovk! 

@cthoyt I agree, I should add something to the webpage to tell the user that this feature exists

**Comment by psincraian** [comment]
Now I show an example of how to use the * operator :-)
