### ISSUE TITLE
Website not working on mobile

### ISSUE THREAD

**Issue by w0rmr1d3r** [psincraian/pepy#481]
Hello @psincraian
Really great project!
I haven't seen the option to open issues on the frontend repo, so opening it here.
The website for mobile (Safari - iOS) doesn't low anything after searching for a package.
It gets stucked in the loading spin.

Any idea why is that? Is there a workaround?

Thank you 🤗

**Comment by psincraian** [comment]
Hey! Sorry @w0rmr1d3r , the server was down for some reason, I still need to check what happened :thinking:

**Comment by psincraian** [comment]
Seems that is still down, I will dive deep on the error as soon as possible

**Comment by w0rmr1d3r** [comment]
Thank you @psincraian 
I tried later today and it worked for both mobile and desktop.
Same URL, at the same time.

Hope the issue is fixed 👌

**Comment by Teekeks** [comment]
Does not look like its fixed: same problem happening on desktop right now

**Comment by braniii** [comment]
It seems that the servers are down again

**Comment by psincraian** [comment]
sometimes there is a huge spike on traffic and the server crashes because it doesn't have enough resources. Will try to add some autoscaling, but it would require some time

**Comment by psincraian** [comment]
These days I have been working on improving the performance of the service. Now the response time should be much faster and the resource usage have dropped also. Hopefully, this will resolve the problem :-)

![image](https://user-images.githubusercontent.com/17912624/208506139-90b255bc-3873-43ee-9b48-50561b4d7594.png)

**Comment by w0rmr1d3r** [comment]
wow! great improvements!
thank you @psincraian for taking care of this 🚀
