### ISSUE TITLE
More responsive view

### ISSUE THREAD

**Issue by gaborbernat** [psincraian/pepy#496]
We should leave align the content rather than the center to make the header not stick out, or that should also be center aligned.

![image](https://user-images.githubusercontent.com/690238/210005255-8efb1526-813a-452b-93b4-9fb12d38182f.png)

Also would be nice to have a wider/more extensive graph. Perhaps via a responsive design?

**Comment by psincraian** [comment]
🤯 what happened here? In theory that should be aligned 🤔

What browser and version are you using?

**Comment by gaborbernat** [comment]
I'm using chrome on Manjaro 😅

**Comment by gaborbernat** [comment]
It's aligned center the content, it's not Fullscreen screenshot as there's just more white emptiness on the right 😅

**Comment by psincraian** [comment]
Ok! So you have a ultra wide monitor, right? 

I think I can fix the top bar 😀

**Comment by gaborbernat** [comment]
Indeed 😊 would appreciate it if maz width cloud be 2x of what is now 😅

**Comment by psincraian** [comment]
I have done some changes in the UI. Can you provide any feedback? I don't have an ultrawide screen so it's difficult to assess from my end

**Comment by gaborbernat** [comment]
<img width="2353" alt="image" src="https://user-images.githubusercontent.com/690238/214675732-da1c09f1-6cbd-4148-9f90-d308862e540f.png">
Looks stellar now, thanks!

**Comment by hugovk** [comment]
The search box now looks very wide:

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/1324225/214684049-cb0deec1-258e-4aae-b0a2-cf82a67b5518.png">

But the actual input is only one small section on the left and the rest doesn't focus the search box on click:

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/1324225/214684209-efe59d85-3fd4-4c71-9903-5f7f792abecc.png">

Should the input be the same width as the search box?

**Comment by psincraian** [comment]
thanks @hugovk! I just fixed the input search box :-)
