### ISSUE TITLE
[Bug] Incorrect counts in the `sum` column for cumulative version wildcards

### ISSUE THREAD

**Issue by jpotyka** [psincraian/pepy#498]
The cumulative version wildcards creating incorrect counts in the `sum` column. Apparently the value of the cumulative graph is also added to the `sum`. Actually, the value should be ignored. Here are two screenshots showing the problem:

Without the wildcard version - Correct counts:
![true_counts](https://user-images.githubusercontent.com/21240743/211410161-f480ebe2-86ab-44e7-8fa9-9ffed3f8438f.png)

With the wildcard version - Incorrect counts:
![false_counts](https://user-images.githubusercontent.com/21240743/211410098-dad503c2-142e-48e6-9bc7-831605392d18.png)

Greetings and thanks for the great tool
Jendrik

**Comment by jpotyka** [comment]
Sorry, I just realised that the frontend is in an extra repository. I can simply close the issue here and open it in the other repository. Should I proceed like this?

**Comment by psincraian** [comment]
It's the right place to open the issue ☺️

Mmm I think this is more an improvement. When I developed this I considered more the case when you want to compare 1.* vs 2.* for example. 

But sincerely not sure if people is using the sum column 🤔 I will ask this in pepy.tech and maybe delete this column
