### ISSUE TITLE
Bug: Blank page when no stable version

### ISSUE THREAD

**Issue by yanyongyu** [psincraian/pepy#502]
According to the frontend source code, `lastVersion` maybe `undefined` if `selectedVersions` is empty list. `indexOf` will fail with error `TypeError: Cannot read properties of undefined (reading 'indexOf')`

https://github.com/psincraian/pepy-front/blob/2cdc8d097d2b8193f72f2d703a67738913c63bf9/src/components/DownloadsComponent.js#L57-L61

Example link: https://pepy.tech/project/nonebot2

**Comment by psincraian** [comment]
It should be fixed now :-)
