### ISSUE TITLE
[BUG] Cannot initialize the project

### ISSUE THREAD

**Issue by lit26** [psincraian/pepy#510]
Hi,
Cannot initialize the project when using `make start-containers`.

![Screen Shot 2023-02-03 at 11 34 44 PM](https://user-images.githubusercontent.com/51225681/216755220-d1eb868a-9b16-4257-b530-653bb7b318af.png)

**Comment by psincraian** [comment]
Sorry, the image wasn't public. Now it is, you can try again and the problem should be fixed :-)

**Comment by lit26** [comment]
Great, check later

**Comment by lit26** [comment]
![Screen Shot 2023-02-28 at 12 13 18 PM](https://user-images.githubusercontent.com/51225681/221968006-480d1e84-0f23-4d4d-aede-5e282c128d0e.png)
There is another one.

**Comment by lit26** [comment]
The test container is also not public. Can you fix this?
