### ISSUE TITLE
Add back the "*" auto-complete option for the version selector

### ISSUE THREAD

**Issue by sethmlarson** [psincraian/pepy#528]
A long time ago there was an auto complete option for "all versions" via "*", but that seems to not be a thing anymore? I have to manually add this in the URL to get a graph of all versions. Thanks again for creating this service! :purple_heart:

**Comment by psincraian** [comment]
Hey @sethmlarson 

If you type the `*` in the version box, it should add it to the graph 🤔 

I will check this week why the suggestion is not there anymore

**Comment by psincraian** [comment]
It should be fixed now :-) thanks for raising the issue

**Comment by sethmlarson** [comment]
Thanks @psincraian!
