### ISSUE TITLE
Grey/blue image won't update

### ISSUE THREAD

**Issue by filipporomani** [psincraian/pepy#544]
If I take [this image](https://static.pepy.tech/personalized-badge/whatsapp-python?period=total&units=none&left_color=yellow&right_color=blue&left_text=Downloads) (yellow/blue) it shows up 1648 downloads.

If I take [this other image](https://static.pepy.tech/personalized-badge/whatsapp-python?period=total&units=none&left_color=grey&right_color=blue&left_text=Downloads) (grey/blue) it shows 1537 (which is the count up to yesterday. The package is the same.

Is this a bug or only a temporary thing? 

Thanks a lot!

**Comment by hugovk** [comment]
Both show 1648 for me, I expect your browser has cached them at different times. Try clearing your browser cache.

**Comment by filipporomani** [comment]
Tried different browsers, different networks and it shows the wrong count.
I tested it out on firefox, chrome, brave, tor, on my phone with WiFi and then with mobile data and the count is the same.
I tested at school and the number is still the same.

I'm just wondering how is this possible lol

**Comment by filipporomani** [comment]
Fixed itself.
