### ISSUE TITLE
pepy.tech 404 error

### ISSUE THREAD

**Issue by seanlaw** [psincraian/pepy#558]
Hi @psincraian! I hope you are doing well. Maybe you are already aware of this and, hopefully, this isn't user error but I am getting a 404 error when trying to reach https://api.pepy.tech/

Is anybody else also seeing this (since July 5th)?

**Comment by psincraian** [comment]
Hey, at the moment you can use: https://api.pepy.tech/api/v2/projects/requests 

But the problem is that there are some clients that are doing too many requests and put the service under high load. So the plan is that in the future the API will continue to be free but I will add auth to limit the number of requests per minute.

**Comment by seanlaw** [comment]
> Hey, at the moment you can use: https://api.pepy.tech/api/v2/projects/requests

Thank you, @psincraian! That worked perfectly. 

> But the problem is that there are some clients that are doing too many requests and put the service under high load. So the plan is that in the future the API will continue to be free but I will add auth to limit the number of requests per minute.

Understood. I only call the service one time per day and am always grateful for your continued support. Please let me know if you need anybody to help test out the auth mechanism in the future. Thank you again!

**Comment by seanlaw** [comment]
> So the plan is that in the future the API will continue to be free but I will add auth to limit the number of requests per minute.

Hello @psincraian! I hope you are doing well. I have been getting a new `{"message":"Invalid API Key"}` error since two days ago and so I signed up for a new account at `pepy.tech`. Maybe I'm just to eager/early but I wasn't able to generate an API key after choosing a name for the API key and clicking the `Create API Key` button. Would you happen to have any suggestion on how I might resolve this or help with testing? Thanks in advance

**Comment by psincraian** [comment]
Hey sorry!

You found the first bug! I tested it but I had hardcoded the cookie name for my user only. Now it's fixed and it should work fine :)

**Comment by seanlaw** [comment]
Thank you @psincraian! I was able to get it working and integrated with my daily triggered [Github Actions workflow](https://github.com/seanlaw/stumpy_growth/blob/master/.github/workflows/schedule.yml). Very painless! I appreciate your continued support and quick response.

**Comment by psincraian** [comment]
Thanks for your patience and understanding also ☺️
