### ISSUE TITLE
Badges stopped working

### ISSUE THREAD

**Issue by pomponchik** [psincraian/pepy#576]
Hi! I am a big fan of your project and have added badges with the number of downloads to the README of all my open source libraries. However, now I have a problem: all these badges suddenly stopped being displayed correctly on the project pages. Here is [an example](https://github.com/pomponchik/polog) of my project with such a problem, I also attach a screenshot.

![It looks like that](https://i.ibb.co/Jd1qv9T/2023-08-29-23-07-20.png)

**Comment by RobWen** [comment]
[![Downloads](https://static.pepy.tech/badge/polog/month)](https://pepy.tech/project/polog)
[![Downloads](https://static.pepy.tech/badge/polog)](https://pepy.tech/project/polog)

[![Downloads](https://static.pepy.tech /badge/polog/month)](https://pepy.tech/project/polog)
[![Downloads](https://static.pepy.tech /badge/polog)](https://pepy.tech/project/polog)

Just delete the blank character here and copy this in your readme

**Comment by pomponchik** [comment]
@RobWen thank you! It works for me. Please note that on the website [pepy.tech](https://www.pepy.tech/) badge copy buttons don't work.

**Comment by psincraian** [comment]
Should be fixed now :)
