### ISSUE TITLE
Broken badges

### ISSUE THREAD

**Issue by sepandhaghighi** [psincraian/pepy#596]
@psincraian ✋ 

The badge images in GitHub `README` are not working correctly.
It appears that the images in GitHub `README` were broken due to a redirection from `http://pepy.tech/badge/package_name` to `https://static.pepy.tech/badge/package_name`.

Examples:

1. [Art](https://github.com/sepandhaghighi/art)
2. [PyCM](https://github.com/sepandhaghighi/pycm)
3. [Samila](https://github.com/sepandhaghighi/samila)
4. [PyMilo](https://github.com/openscilab/pymilo)

Do you think you can solve it on your end, or do we need to update all of the repositories?!

SH

**Comment by psincraian** [comment]
Fixed! Thanks for the headsup, we had 4 redirects and that is why Github didn't show the images 🤦
