### ISSUE TITLE
Redirect to HTTPS

### ISSUE THREAD

**Issue by hugovk** [psincraian/pepy#60]
If you visit an HTTP version of a page, it should redirect to the HTTPS version. 

For example:

* http://pepy.tech/ -> https://pepy.tech/
* http://pepy.tech/project/pip -> https://pepy.tech/project/pip

**Comment by psincraian** [comment]
I will implement this this weekend! :smile: 

Thanks for the suggestion :wink:

**Comment by psincraian** [comment]
Done :blush:
