### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by techtolentino** [psincraian/pepy#631]
Trying to use the pepy.tech api to get download stats for `qiskit-terra`, and running into this issue: 

> Status details:
>
> Server message: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

Please let us know if there's something we can do.

**Comment by gabemorris12** [comment]
I noticed this too and came here. Also, it would be better to change the "please report it to @psincraian at Twitter/X" part of the message to "please see submit or view issues [here](https://github.com/psincraian/pepy/issues)".

**Comment by psincraian** [comment]
Thanks for raising this, seems that a dependabot update broke the service. I will try to add something to prevent this happening in the future.


I also update the error message :)
