### ISSUE TITLE
Vertical scale: 0, 3.5M, 7M, 0.5M, 14M

### ISSUE THREAD

**Issue by hugovk** [psincraian/pepy#632]
https://www.pepy.tech/projects/python-dateutil?versions=* looks like:

![image](https://github.com/psincraian/pepy/assets/1324225/59853c73-8d10-4f3e-b441-d6799e996736)

Note the vertical axis scale: 0, 3.5M, 7M, _0.5M_, 14M

That 0.5M looks incorrect.

Other graphs look okay, for example: https://www.pepy.tech/projects/six?versions=*

**Comment by hugovk** [comment]
https://www.pepy.tech/projects/botocore?versions=* has 0, 5.5M, 11M, _6.5M_, 22M:

![image](https://github.com/psincraian/pepy/assets/1324225/669eccec-31c8-4430-a431-e7e17862b00c)

**Comment by psincraian** [comment]
You are totally right, let me fix those on the next newsletter :)

**Comment by hugovk** [comment]
These are on the website, not the newsletter. Thanks!

**Comment by psincraian** [comment]
fixed :)
