### ISSUE TITLE
[Maybe a bug] Cannot display download data in recent days

### ISSUE THREAD

**Issue by SWHL** [psincraian/pepy#637]
I want to see the data in recent days about `rapidocr_onnxruntime`, but it can not display correctly. 
The package link is : https://www.pepy.tech/projects/rapidocr_onnxruntime. It likes the following:
![image](https://github.com/psincraian/pepy/assets/28639377/c2fa4147-b424-4f7c-b461-fa9458e925f6)

The page cannot display download data between 03-04 and 03-07.

**Comment by psincraian** [comment]
can you see it now?

**Comment by SWHL** [comment]
Now, it is ok. Thanks.
