### ISSUE TITLE
PyPI Infra Incident Impacting BigQuery dataset

### ISSUE THREAD

**Issue by ewdurbin** [psincraian/pepy#679]
Hello! We are tracking an incident that impacted (is impacting?) the BigQuery data sets.

It is evident in the dropoff of stats over the last week. We are currently working to backfill the data, so your stats may need to similarly be backfilled.

I'll leave this issue open for now and notify when we believe we have caught up.

**Comment by psincraian** [comment]
Thanks for the headsup @ewdurbin ☺️

**Comment by ewdurbin** [comment]
There are two phases to our recovery, one is catching up on the backlog of processing and the other is publishing the results to BigQuery.

We're currently in that first phase, and it will take 1-2 days to reprocess the week. More updates on Saturday or Sunday.

**Comment by ewdurbin** [comment]
OK. Our BigQuery dataset is as recovered as we're able. It looks like we lost some data for June 18th unfortunately.

<img width="593" alt="Screenshot 2024-06-22 at 8 25 28 AM" src="https://github.com/psincraian/pepy/assets/1200832/8b638c54-f7fe-45f8-aee1-3ec85c43e2c4">

I think downstream users are good to sync their stats now.
