### ISSUE TITLE
Add a bit of documentation on where data comes from

### ISSUE THREAD

**Issue by dhermes** [psincraian/pepy#68]
First of all, thanks a lot for this awesome and well polished website. I don't want this to feel like I'm criticizing your work.

I'm a bit unclear on why the `pepy` number ([122,332][1]) for my package is so much larger than the one reported by the BigQuery dataset:

```
$ .../bin/pypinfo bezier
Served from cache: True
Data processed: 0.00 B
Data billed: 0.00 B
Estimated cost: $0.00

| download_count |
| -------------- |
|         14,253 |

```

I realize the PyPI dropped a bunch of historical data, so I assume you're cobbling together download data from multiple sources?

[1]: https://pepy.tech/project/bezier

**Comment by psincraian** [comment]
Hi! :blush: 

All the data comes from the official BigQuery database, if I execute the following query in the BigQuery:
```sql
SELECT file.project, COUNT(*) as download_count
FROM TABLE_DATE_RANGE(
  [the-psf:pypi.downloads],
  TIMESTAMP("2000-01-01"),
  CURRENT_TIMESTAMP()
)
WHERE file.project = 'bezier'
GROUP BY file.project
```

I get the following response:
![image](https://user-images.githubusercontent.com/17912624/46038383-3141d880-c10b-11e8-8479-f2f9dbe02e9f.png)

that is nearly the total count of shown in [pepy.tech](pepy.tech). I don't know how pypinfo works and gets the data but it seems that is calculating only the past month downloads only.

Hope this helps you :smile:

**Comment by dhermes** [comment]
Thanks a lot, seems I am confused :grinning:

**Comment by dhermes** [comment]
https://github.com/ofek/pypinfo/pull/51 is the relevant place where the `--all` flag was added

**Comment by dhermes** [comment]
The `--days=30` default is what I was missing. I needed to RTFM and then there would've been no issues.
