### ISSUE TITLE
Use new PyPI attribute to differentiate CI downloads from direct user downloads

### ISSUE THREAD

**Issue by joelostblom** [psincraian/pepy#693]
The ability to differentiate automated installs from manual ones was recently added in pip and PyPI; see https://github.com/pypa/pip/issues/5499 and https://github.com/pypi/linehaul-cloud-function/issues/9 for details. It would be valuable to have this functionality available on pepy.tech to be able to see how many users are directly installing the package. A similar tool that added this recently was pypinfo and the approach can be seen here in case it is helpful https://github.com/ofek/pypinfo/pull/157

**Comment by psincraian** [comment]
Hey,

Thanks for the heads up. I will take a look and add it as many people is interested.

**Comment by psincraian** [comment]
Feature is live on production 🚀
