### ISSUE TITLE
The website seems to be inaccessible after being rectified

### ISSUE THREAD

**Issue by PythonSJL** [psincraian/pepy#714]
Here is the content displayed on the website:

Something went wrong!
There was an internal server error, please see submit or view issues [here](https://github.com/psincraian/pepy/issues).
Status details:
Server message: r.versions.toReversed is not a function

![123321](https://github.com/user-attachments/assets/cb1b9c3a-f7c9-4069-b4b5-ed176deec4c6)

**Comment by psincraian** [comment]
mmmm can you try to clean the cache? 🤔

**Comment by PythonSJL** [comment]
> mmmm can you try to clean the cache? 🤔

I cleared the cache, but it had no effect. Have you ever changed servers? :-)

**Comment by psincraian** [comment]
It's a strange bug, I only had one error today in the frontend (I'm using next.js) and I can access perfectly ![image](https://github.com/user-attachments/assets/9190dc91-1683-4705-a72a-ff5125436e9b)

**Comment by PythonSJL** [comment]
Now the website is just starting to enter the statistics page, and then it flashes to the error page within one second...
I have tried using many browsers, but they all have the same problem.
I think there may be compatibility issues when the browser loads certain data.
Did you use code that is not supported by certain browsers for this page?

## Here is the information on the error page:

Something Went Wrong
We encountered an error while fetching data for pypynum

** Error: a.versions.toReversed is not a function **
What you can try:

Refresh the page to try again
Clear your browser cache and cookies
Check your internet connection
If the error persists, please report it on GitHub
Try Again
[Report Issue](https://github.com/psincraian/pepy/issues/new)
Error ID:

(Error ID is empty)

**Comment by psincraian** [comment]
Do you have the same problem for all packages? 

I tried multiple times to reproduce the issue but I cannot 😢 what browser are you using? Do you have any plugins?

**Comment by PythonSJL** [comment]
> Do you have the same problem for all packages?
> 
> I tried multiple times to reproduce the issue but I cannot 😢 what browser are you using? Do you have any plugins?

Now I have discovered a very strange problem: if I directly enter Google Chrome to search, an error interface will appear; If I enter Google Chrome through the QQ chat history link, it will display normally.

**Comment by psincraian** [comment]
I see another user that has the same problem as you https://github.com/psincraian/pepy/issues/718

Which browser and version do you hav?

**Comment by arcctgx** [comment]
I saw the same problem, and in my case it was a client-side issue. When opening the page in Mozilla Firefox 113 I could see the following error in the browser console:

```
TypeError: a.versions.toReversed is not a function
```

`toReversed()` is not supported in older browser versions [1]. The problem went away after upgrading to the latest version of Mozilla Firefox.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toReversed#browser_compatibility

**Comment by PythonSJL** [comment]
> I see another user that has the same problem as you #718
> 
> Which browser and version do you hav?

I found that I have two versions of Google Chrome, versions 102.0.5005.115 and 130.0.6723.92, so it should be the old version that has compatibility issues.

**Comment by PythonSJL** [comment]
I think you can add instructions on the homepage of this website to guide users in updating to the latest version of the browser :-)

**Comment by psincraian** [comment]
Added an line on the error page
