### ISSUE TITLE
Error: connection closed

### ISSUE THREAD

**Issue by koaning** [psincraian/pepy#719]
I seem to be hitting this issue over and over. Figured that I should report it. 

![CleanShot 2024-11-04 at 11 03 56](https://github.com/user-attachments/assets/4fdf04cd-c5f2-4acd-a9f9-361f2922e932)

**Comment by psincraian** [comment]
Let me check that issue, I think we have some spikes in traffic that overloads our service

**Comment by psincraian** [comment]
Have you faced this issue more times?

**Comment by koaning** [comment]
Actually no, lemme close this issue.
