### ISSUE TITLE
Beta releases are showing by default

### ISSUE THREAD

**Issue by ZhiyuanChen** [psincraian/pepy#730]
Hi, 

Thank you for this excellent project. 

I encountered an issue that my beta releases are showing on the page by default, 

![image](https://github.com/user-attachments/assets/74ac4cef-2e39-4bee-935b-7e4f7d56b26b)

And I have to manually select the current release. 

![image](https://github.com/user-attachments/assets/20644198-9a16-4e37-9093-522d76db9231)

**Comment by psincraian** [comment]
Thanks for reporting, I will exclude them for the beta

**Comment by psincraian** [comment]
fixed!

**Comment by ZhiyuanChen** [comment]
Nice!!! 
Thank you!
