### ISSUE TITLE
Handle package name escaping

### ISSUE THREAD

**Issue by althonos** [psincraian/pepy#89]
Hi there ! First of all, thanks a lot for this web app, it's finally fun to search for project metadata.

Now comes the time I nitpick: as the proud owner of the [`fs.sshfs`](https://pypi.org/project/fs.sshfs/), I wanted to check its metadata. Unfortunately, it does seem like PePy is storing the package using the PyPI canonical name: `fs-sshfs`, and I can access to it like so.

Since there are some other packages with dots in their names on PyPI, it would be great if those were escaped as dashes when trying to query PePy for their stats !

**Comment by psincraian** [comment]
I will take a look at this issue this weekend. 

Thanks for the report :+1:

**Comment by psincraian** [comment]
Sorry for the delay... I already fixed that. Many thanks for the report :blush:
