### ISSUE TITLE
FYI you should know about http://pypistats.org/

### ISSUE THREAD

**Issue by njsmith** [psincraian/pepy#96]
I'm not saying you and @crflynn need to join forces or anything, but just in case you didn't know about each other...

**Comment by psincraian** [comment]
Thanks for the information, I will be happy to join forces! :blush: @crflynn if you want to reach me you can do it at psincraian@gmail.com :wink:

**Comment by ishiland** [comment]
@psincraian any reason the stats are different for some packages between these 2 websites?

For example, the stats here: https://pypistats.org/packages/python-geosupport

are far different than they are on pepy: https://pepy.tech/project/python-geosupport

**Comment by ishiland** [comment]
So it seems Without_Mirrors is a more accurate representation in my case.  Thanks for the clarification.
